name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    container:
      image: docker.io/calacaly/rust-builder:latest
    steps:
      - name: actions/checkout@v3
      - uses: actions/checkout@v3
      - name: Scan for vulnerabilities
        run: cargo audit
