name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test   
    runs-on: ubuntu-latest
    container:
      image: docker.io/calacaly/rust-builder:latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Run tests
        run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    container:
      image: docker.io/calacaly/rust-builder:latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Enforce formatting
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    container:
      image: docker.io/calacaly/rust-builder:latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Linting
        run: cargo clippy -- -D warnings

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    container:
      image: docker.io/calacaly/rust-builder:latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        
      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --workspace
